/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Color: typeof import('./components/color/index.vue')['default']
    GlobalHeader: typeof import('./components/GlobalHeader.vue')['default']
    GlobalNestedRouterView: typeof import('./components/global-nested-router-view/index.vue')['default']
    OrgTreeSelect: typeof import('./components/OrgTreeSelect.vue')['default']
    Result: typeof import('./components/result/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TConfigProvider: typeof import('tdesign-vue-next')['ConfigProvider']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    Thumbnail: typeof import('./components/thumbnail/index.vue')['default']
    TInput: typeof import('tdesign-vue-next')['Input']
    TLink: typeof import('tdesign-vue-next')['Link']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TPopconfirm: typeof import('tdesign-vue-next')['Popconfirm']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TTable: typeof import('tdesign-vue-next')['Table']
    TTag: typeof import('tdesign-vue-next')['Tag']
  }
}
