package com.permission.user.vo;

import lombok.Builder;
import lombok.Data;

/**
 * 重置密码VO
 */
@Data
@Builder
public class ResetPasswordVO {

    /**
     * 临时密码
     */
    private String temporaryPassword;

    /**
     * 是否自动生成
     */
    private Boolean autoGenerated;
}
